### ISSUE TITLE
Enhancement | The folder construction of this project

### ISSUE THREAD

**Issue by iNorthIsle** [SeeDAO-OpenSource/DEV-NoviceVillage#8]
it's better to have the specification (naming, construction) for better collaboration

**Comment by 0xRory** [comment]
Thanks for the suggestion, I added page 

[协作格式](https://github.com/SeeDAO-OpenSource/DEV-NoviceVillage/tree/master/%E5%A6%82%E4%BD%95%E5%85%B1%E5%90%8C%E5%8D%8F%E4%BD%9C/%E5%8D%8F%E4%BD%9C%E6%A0%BC%E5%BC%8F)
